services:
  mysql:
    image: mysql:8.4
    container_name: inventory-mysql
    env_file:
      - .env
    ports:
      # Map host port 3307 to MySQL container port 3306
      - "3307:3306"
    volumes:
      # Keep MySQL data after the container is removed
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: inventory-app
    env_file:
      - .env
    depends_on:
      - mysql
    # volumes:
    #   # Mount local app folder into the container for development
    #   - ./app:/app
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  mysql_data: